name: coherent
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.3.0
  - asttokens=3.0.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.6.15
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.12.11
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - ffmpeg=4.3
  - filelock=3.18.0
  - fontconfig=2.14.2
  - fonttools=4.58.4
  - freetype=2.12.1
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - grpcio=1.62.2
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.15
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.78.4
  - libgomp=15.1.0
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libpng=1.6.43
  - libpq=17.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - markdown=3.8.1
  - markupsafe=3.0.2
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.5
  - numba=0.61.2
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.5
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1.1
  - platformdirs=4.3.8
  - ply=3.11
  - prompt-toolkit=3.0.51
  - protobuf=4.25.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.4
  - setuptools=80.9.0
  - sip=6.10.0
  - six=1.17.0
  - slicer=0.0.8
  - sqlite=3.46.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.13.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - termcolor=3.1.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.45
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - arviz==0.21.0
      - backports-tarfile==1.2.0
      - cachetools==6.1.0
      - click==8.2.1
      - cons==0.4.6
      - cython==3.1.2
      - dask==2025.5.1
      - emcee==3.1.6
      - emukit==0.4.11
      - etuples==0.3.9
      - fsspec==2025.5.1
      - gpy==1.13.2
      - h5netcdf==1.6.1
      - h5py==3.14.0
      - imbalanced-learn==0.13.0
      - locket==1.0.0
      - logical-unification==0.4.6
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - minikanren==1.0.3
      - multipledispatch==1.0.0
      - paramz==0.9.6
      - partd==1.4.2
      - pyarrow==20.0.0
      - pymc==5.22.0
      - pytensor==2.30.3
      - rich==14.0.0
      - scikit-learn==1.6.1
      - scipy==1.12.0
      - seaborn==0.13.2
      - shap==0.41.0
      - sklearn-compat==0.1.3
      - snap==0.5
      - toolz==1.0.0
      - torch==2.7.1
      - torchvision
      - torchaudio
      - xarray==2025.6.1
      - xarray-einstats==0.9.1
      - -e /home/tidmad/bliu/resum-coherent
prefix: /home/tidmad/miniconda3/envs/coherent
